---
title:               开心工作每一天
word:                微大学后台

#皮肤选择
classic:             经典
cerulean:            蔚蓝
redy:                艳红
journal:             日志
simplex:             简约
slate:               单一
spacelab:            浅灰
united:              菊黄

#工作菜单
index:               主页
stores:              店家管理
users:               用户管理
orders:              订单管理

