index_color:
  -
    s:
      53A40B
    q:
      DDFFDD
    image:
      /images/home_bg_color/bgcolor_1.png
  -
    s:
      F81A01
    q:
      FFE8E8
    image:
      /images/home_bg_color/bgcolor_2.png
  -
    s:
      FFBF00  
    q:
      FFFFE8    
    image:
      /images/home_bg_color/bgcolor_4.png
  -
    s:
      942CD2 
    q:
      FFDDFF
    image:
      /images/home_bg_color/bgcolor_3.png
  -
    s:
      605791
    q:
      E8E6F0
    image:
      /images/home_bg_color/bgcolor_5.png