super_market:
   饮品:
    tag1:
        康师傅
    tag2:
        统一
    tag3:
        可乐/汽水
    tag4:
        凉茶
    tag5:
        矿泉水
    tag6:
        其他
   食品:
    tag1:
       方便面
    tag2:
       面包
    tag3:
       奶制品
    tag4:
       小吃  
   生活用品:
    tag1:
        纸巾
    tag2:
        沐浴用品
    tag3:
        牙膏牙刷
     